### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by codyn329** [codyn329/Material#2]
- [ ] Create JS animations and transitions 
- [ ] Add CSS for web components
- [ ] Add submodules for the two fonts: Roboto, Roboto Mono
- [ ] Browser support should be for: Chrome, Firefox, Safari, Opera, and IE(not sure what version?), and Edge
- [ ] Should gracefully degrade across devices: Laptop --> Tablet --> Phone (currently iOS and Android)
- [ ] Skin should be compatible with MediaWiki version 1.23 through 1.25, and hopefully 1.26 when its released ( no support for 1.19, 1.20, 1.21, and 1.22 since they're obsolete according to https://www.mediawiki.org/wiki/Version_lifecycle )
- [ ] Make sure skin is compatible (this means all the functions of the extensions should still work with little rewriting / no rewriting of the skin itself) with the following extensions... 
 - [ ] SocialProfile
 - [ ] Echo
 - [ ] VisualEditor(VE) 
 - [ ] UniversalLanguageSelector 
- [ ] Send interface messages for translation at https://translatewiki.net/
- [ ] Validate markup via https://validator.w3.org/
- [ ]  Make sure code follows MediaWiki coding conventions via https://www.mediawiki.org/wiki/Manual:Coding_conventions
- [ ] **[extra/idea]** - `position: fixed;`
 table of contents for easy navigation at any given time? 
- [ ] **[extra/idea]** - Create a simple way to change theme of skin
- [ ] **[idea]** - Add support for advertisements

**Comment by MtMNC** [comment]
I've wanted to incorporate material design into Refreshed for a while, it's so pretty :D I'd love to help out!

**Comment by codyn329** [comment]
Yep, the design language is quite beautiful :D Also, that's great! I'm going to separate the contribute section from README.md and move it to CONTRIBUTING.md per https://github.com/blog/1184-contributing-guidelines, so just check the repo out later and it should be created by then. And yeah saw that google repo actually, just not at the time this ticket was created. Thanks for mentioning it though, just edited it. It'd be cool if Refreshed integrated material design/material design icon font into the skin :)

**Comment by codyn329** [comment]
Oh, in case you're wondering of how it looks, the testing site I use is at http://codyn329.x10host.com/index.php/Main_Page. Very experimental right now since the project is of course in alpha phase, although I try to keep the files updated as possible with the github project. (**NOTE:** x10hosting's MediaWiki software provider probably isn't is accurate as the official MediaWiki software so I'm trying to find a different way to do this)

**Comment by MtMNC** [comment]
@codyn329 Thanks for the link. I set it up on my local clone as well and it looks the same there, so I think you're fine. :)

I messed around a bit, here's what I came up with. No idea if it's what you're going for at all, but it's at https://github.com/MtMNC/Material if you're interested.

<img width="1208" alt="screen shot 2015-08-24 at 11 57 31 am" src="https://cloud.githubusercontent.com/assets/5515877/9449418/56425840-4a57-11e5-930d-8b78079eef66.png">

**Comment by codyn329** [comment]
Thanks, it looks really great :D I'll push these to the main repo (btw: I'm going to readd the if statement for ```newtalk``` notifications, but I assumed you commented it out so you can show how it would look like :P) Oh and also I added you to the list of authors for the skin :)

**Comment by MtMNC** [comment]
@codyn329 Oh yeah you're right, guess I did forget to add that back in. That was exactly why. And thanks :D

**Comment by codyn329** [comment]
**UPDATE**: Added new task to main list: Test CSS stylesheets for directionality support (LTR and RTL)

Also, this thread will be for the main todo list, and each task will eventually have their own issue so discussion is organized and not mumbo-jumboed into one giant discussion. :P

**Comment by codyn329** [comment]
Going to try and set up a local host soon, but for the mean time I'll be using x10hosting's web servers
